<a href="https://colab.research.google.com/github/sophiessss29/NLP-Course/blob/main/co_occurence_Shumilova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import defaultdict
import re

In [2]:
file_path = 'Stanford.txt'

In [3]:
with open(file_path, 'r', encoding='utf-8') as file:
  text = file.read()

In [4]:
text = text.lower()
text[500:1000]

"d died in 1893 and again after much of the campus was damaged by the 1906 san francisco earthquake.[13] following world war ii, university provost frederick terman inspired an entrepreneurial culture to build a self-sufficient local industry (later silicon valley).[14] in 1951, the stanford research park was established in palo alto and is the world's first university research park.[15] by 2021, the university had 2,288 tenure-line faculty, senior fellows, center fellows, and medical faculty on "

In [5]:
text = re.sub(r'[^a-z\s\.\?!]', '', text)
text[500:1000]

'e campus was damaged by the  san francisco earthquake. following world war ii university provost frederick terman inspired an entrepreneurial culture to build a selfsufficient local industry later silicon valley. in  the stanford research park was established in palo alto and is the worlds first university research park. by  the university had  tenureline faculty senior fellows center fellows and medical faculty on staff.\n\nthe university is organized around seven schools of study on an acre hect'

In [6]:
sentences = re.split(r'[\.\?!]', text)
sentences[1:3]

[' it was founded in  by railroad magnate leland stanford the eighth governor of and thenincumbent senator from california and his wife jane in memory of their only child leland jr',
 '\n\nthe university admitted its first students in  opening as a coeducational and nondenominational institution']

In [7]:
sentences = [sentence.split() for sentence in sentences if sentence]
sentences[3]

['it',
 'struggled',
 'financially',
 'after',
 'leland',
 'died',
 'in',
 'and',
 'again',
 'after',
 'much',
 'of',
 'the',
 'campus',
 'was',
 'damaged',
 'by',
 'the',
 'san',
 'francisco',
 'earthquake']

In [37]:
co_occurrence = defaultdict(lambda: defaultdict(int))

In [40]:
def update_co_occurrence(sentence, window_size=1):
    words = ["<START>"] + sentence + [""]
    for i, word in enumerate(words):
        for j in range(max(0, i - window_size), min(len(words), i + window_size + 1)):
            if i != j:
                co_occurrence[word][words[j]] += 1

for sentence in sentences:
    update_co_occurrence(sentence)

co_occurrence['campus']

defaultdict(int,
            {'the': 21,
             'was': 3,
             'hectare': 3,
             'one': 6,
             'cornell': 3,
             'to': 6,
             'stanford': 9,
             '': 18,
             'in': 9,
             'commercial': 3,
             'on': 21,
             'km': 3,
             'main': 12,
             'includes': 6,
             'also': 3,
             'central': 6,
             'is': 3,
             'for': 3,
             'mail': 3,
             'of': 9,
             'contemporary': 3,
             'landmarks': 3,
             'primarily': 3,
             'and': 3,
             'core': 3,
             'are': 3,
             'at': 3,
             'drive': 3,
             'due': 3,
             'has': 3,
             'since': 3,
             'studentrun': 3,
             'rag': 3,
             'sustainability': 3,
             'although': 3,
             'with': 3,
             'stanfords': 3,
             'climate': 3,
             'analyzed': 3,
             'rape': 3,
             'rapes': 3,
             'from': 3,
             'after': 3,
             'ban': 3})

In [41]:
tokens = list(co_occurrence.keys())
tokens[:10]

['<START>',
 'stanford',
 'university',
 'officially',
 'leland',
 'junior',
 'is',
 'a',
 'private',
 'research']

In [42]:
co_occurrence_df = pd.DataFrame(co_occurrence).fillna(0).astype(int).reindex(tokens, columns=tokens, fill_value=0)
co_occurrence_df

,<START>,stanford,university,officially,leland,junior,is,a,private,research,...,gdel,knuth,ijcai,computers,thought,grace,murray,foundations,forbes,produced
<START>,0,138,0,0,0,0,0,6,0,3,...,0,0,0,0,0,0,0,0,0,0
stanford,138,0,39,0,24,6,51,3,0,15,...,0,0,0,0,0,0,0,0,3,0
university,0,39,0,3,0,6,18,0,0,9,...,0,0,0,0,0,0,0,0,0,0
officially,0,0,3,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
leland,0,24,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
grace,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,3,0,0,0
murray,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
foundations,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
forbes,0,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
produced,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0